#can be many wiki & many www sites

[server]
port = 3000
addr = "0.0.0.0"


[[wiki]]
name = "sdk"
title = "Grid Manual"
url = "github.com/threefoldfoundation/info_tfgridsdk"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "production"
groups = ["admin"]
auth = true

[[wiki]]
name = "sdk2"
title = "Grid Manual Staging"
url = "github.com/threefoldfoundation/info_tfgridsdk"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"


[[wiki]]
name = "wiki"
url = "https://github.com/threefoldfoundation/info_threefold"
title = "ThreeFold Wiki"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "production"

[[wiki]]
name = "wiki2"
title = "ThreeFold Wiki Staging"
#http or git url
url = "https://github.com/threefoldfoundation/info_threefold"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"


#website
[[www]]
name = "freetft"
url = "git@github.com:threefoldfoundation/www_getfreetft.git"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = ""
environment = "production"


#website
[[www]]
name = "threefold"
url = "git@github.com:threefoldfoundation/www_threefold.io_new.git"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = "html"
environment = "production"

[[www]]
name = "incubaid"
url = "git@github.com:Incubaid/www_incubaid.git"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = ""
environment = "production"

#website
[[www]]
name = "freeflownation"
url = "https://github.com/freeflownation/www_freeflownation"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = "html"
environment = "production"

#data of simulator exports
[[data]]
name = "simexports"
title = "Simulator data repo"
url = "https://github.com/threefoldfoundation/simulator_export"
path = ""
autocommit = false
branch = "master"
branchswitch = true
srcdir = "html"
environment = "production"
