#can be many wiki & many www sites

[server]
port = 3000
addr = "0.0.0.0"




[[wiki]]
#unique name for the wiki
name = "matchmakers"
#http or git url
url = "git@github.com:threefoldfoundation/info_matchmakers.git"
#if empty will be auto created
path = ""
#commit automatically when there is new info, only works when ssh used
autocommit = false
#branch name, of "" then will be the default or what is found on the FS
branch = "master"
#switch branch automatically if the name given above and its different on FS
branchswitch = false
#path in the repo where the info is, std "src"
srcdir = "src"
#environment name (for example:  production, staging, test), is used to define location where code will be checked out is ~/$environment/code/...
#if empty then is ~/sandbox/code
environment = "production"
auth = true
domain = "matchmakers.threefold.io"

[[wiki]]
#unique name for the wiki
name = "matchmakers2"
#http or git url
url = "git@github.com:threefoldfoundation/info_matchmakers.git"
#if empty will be auto created
path = ""
#commit automatically when there is new info, only works when ssh used
autocommit = false
#branch name, of "" then will be the default or what is found on the FS
branch = "development"
#switch branch automatically if the name given above and its different on FS
branchswitch = false
#path in the repo where the info is, std "src"
srcdir = "src"
#environment name (for example:  production, staging, test), is used to define location where code will be checked out is ~/$environment/code/...
#if empty then is ~/sandbox/code
environment = "testing"
auth = true
domain = "matchmakers2.threefold.io"


[[wiki]]
#unique name for the wiki
name = "ambassadors"
#http or git url
url = "git@github.com:threefoldfoundation/info_ambassadors.git"
#if empty will be auto created
path = ""
#commit automatically when there is new info, only works when ssh used
autocommit = false
#branch name, of "" then will be the default or what is found on the FS
branch = "development"
#switch branch automatically if the name given above and its different on FS
branchswitch = false
#path in the repo where the info is, std "src"
srcdir = "src"
#environment name (for example:  production, staging, test), is used to define location where code will be checked out is ~/$environment/code/...
#if empty then is ~/sandbox/code
environment = "production"
auth = true
domain = "ambassadors.threefold.me"


[[wiki]]
name = "advisors"
url = "git@github.com:threefoldfoundation/info_advisors.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "production"
auth = true
domain = "advisors.threefold.me"


[[wiki]]
name = "board"
url = "git@github.com:threefoldfoundation/info_board.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "production"
auth = true
domain = "board.threefold.me"


[[wiki]]
name = "sdk_jsx"
title = "Grid Manual"
url = "https://github.com/threefoldfoundation/info_gridmanual"
path = ""
autocommit = false
branch = "master_jsx"
branchswitch = false
srcdir = "src"
environment = "legacy"
domain = "sdk.threefold.io"





[[wiki]]
name = "legal"
title = "Legal"
url = "git@github.com:threefoldfoundation/legal.git"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = "production"
domain = "legal.threefold.io"



[[wiki]]
name = "manual2"
title = "Grid Manual Staging"
url = "https://github.com/threefoldfoundation/info_gridmanual"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
domain = "manual2.threefold.io"




[[wiki]]
name = "manual"
title = "Grid Manual"
url = "https://github.com/threefoldfoundation/info_gridmanual"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = "production"
domain = "manual.threefold.io"


[[wiki]]
name = "wiki"
url = "https://github.com/threefoldfoundation/info_foundation"
title = "ThreeFold Wiki"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = "production"
domain = "wiki.threefold.io"


[[wiki]]
name = "wiki2"
title = "ThreeFold Wiki Staging"
#http or git url
url = "https://github.com/threefoldfoundation/info_foundation"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
domain = "wiki2.threefold.io"

[[wiki]]
name = "wmazraa"
url = "https://github.com/mazraa/info_mazraa"
title = "Mazraa Wiki"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = "production"
domain = "wiki.mazraa.io"


[[wiki]]
name = "w2mazraa"
title = "Mazraa Wiki Staging"
#http or git url
url = "https://github.com/mazraa/info_mazraa"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
domain = "wiki2.mazraa.io"

[[wiki]]
name = "vdr"
title = "Virtual Data Room"
url = "https://github.com/threefoldfoundation/info_vdr"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = "production"
domain = "vdr.threefold.tech"


[[wiki]]
name = "vdr2"
title = "Virtual Data Room"
url = "https://github.com/threefoldfoundation/info_vdr"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
domain = "vdr2.threefold.tech"

[[wiki]]
name = "tfnow"
title = "Threefold now"
url = "https://github.com/threefoldfoundation/info_threefold_now"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = "production"
domain = "now.threefold.io"

[[wiki]]
name = "tfnow2"
title = "Threefold now"
url = "https://github.com/threefoldfoundation/info_threefold_now"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
domain = "now2.threefold.io"


[[wiki]]
name = "cw"
title = "Crystalhome Wiki"
#http or git url
url = "https://github.com/crystal-home/info_crystalhome"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = "production"
domain = "wiki.crystalhome.org"


[[wiki]]
name = "cw2"
title = "Crystalhome Wiki Staging"
#http or git url
url = "https://github.com/crystal-home/info_crystalhome"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
domain = "wiki2.crystalhome.org"


[[wiki]]
name = "crystaltwin"
title = "crystaluniverse Wiki production"
url = "github.com/crystaluniverse/info_crystal"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = "production"
domain="wiki.crystaltwin.me"


[[wiki]]
name = "crystaltwin2"
title = "crystaluniverse Wiki Staging"
url = "github.com/crystaluniverse/info_crystal"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
domain="wiki2.crystaltwin.me"


[[wiki]]
name = "bettertoken"
title = "Bettertoken wiki"
url = "https://github.com/BetterToken/info_bettertoken"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = "production"
domain = "wiki.bettertoken.com"

[[wiki]]
name = "bettertoken2"
title = "Bettertoken wiki Staging"
url = "https://github.com/BetterToken/info_bettertoken"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
domain = "wiki2.bettertoken.com"

[[wiki]]
name = "internet9"
title = "internet9 wiki"
url = "https://github.com/threefoldfoundation/info_internet9"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = "production"
domain = "info.internet9.me"

[[wiki]]
name = "internet9_2"
title = "internet9 wiki Staging"
url = "https://github.com/threefoldfoundation/info_internet9"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
domain = "info2.internet9.me"


#website
[[www]]
name = "freetft2"
url = "git@github.com:threefoldfoundation/www_getfreetft.git"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = ""
environment = "testing"


#website
[[www]]
name = "threefold2"
url = "git@github.com:threefoldfoundation/www_threefold.io_new.git"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = "html"
environment = "testing"

[[www]]
name = "incubaid2"
url = "git@github.com:Incubaid/www_incubaid.git"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = ""
environment = "testing"

#website
[[www]]
name = "freeflownation2"
url = "https://github.com/freeflownation/www_freeflownation"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = "html"
environment = "testing"



[[www]]
name = "freetft"
url = "git@github.com:threefoldfoundation/www_getfreetft.git"
path = ""
autocommit = false
branch = "master"
branchswitch = true
srcdir = ""
environment = "production"


#website
[[www]]
name = "threefold"
url = "git@github.com:threefoldfoundation/www_threefold.io_new.git"
path = ""
autocommit = false
branch = "master"
branchswitch = true
srcdir = "html"
environment = "production"

[[www]]
name = "incubaid"
url = "git@github.com:Incubaid/www_incubaid.git"
path = ""
autocommit = false
branch = "master"
branchswitch = true
srcdir = ""
environment = "production"

#website
[[www]]
name = "freeflownation"
url = "https://github.com/freeflownation/www_freeflownation"
path = ""
autocommit = false
branch = "master"
branchswitch = true
srcdir = "html"
environment = "production"


#data of simulator exports
[[data]]
name = "simexports"
title = "Simulator data repo"
url = "https://github.com/threefoldfoundation/simulator_export"
path = ""
autocommit = false
branch = "master"
branchswitch = true
srcdir = "html"
environment = "production"

[[blog]]
name = "tfblog"
title = "Threefold Blog"
#http or git url
url = "https://github.com/threefoldfoundation/www_tfblog"
#if empty will be auto created
path = ""
#commit automatically when there is new info, only works when ssh used
autocommit = false
#branch name, of "" then will be the default or what is found on the FS
branch = "master"
branchswitch = true
#path in the repo where the info is, std "src"
srcdir = ""
#environment name (for example:  production, staging, testing)
environment = "production"
domain = "blog.threefold.io"


[[blog]]
name = "tfblog2"
title = "Threefold Blog Staging"
#http or git url
url = "https://github.com/threefoldfoundation/www_tfblog"
#if empty will be auto created
path = ""
#commit automatically when there is new info, only works when ssh used
autocommit = false
#branch name, of "" then will be the default or what is found on the FS
branch = "development"
branchswitch = true
#path in the repo where the info is, std "src"
srcdir = ""
#environment name (for example:  production, staging, testing)
environment = "testing"
domain = "blog2.threefold.io"
